# Generated by Django 6.0.3 on 2026-04-28 05:53

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=markdownx.models.MarkdownxField(verbose_name="Текст статьи"),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL обложки"
            ),
        ),
    ]
