# Generated by Django 6.0.3 on 2026-04-28 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience",
                    models.CharField(max_length=100, verbose_name="Тренировочный стаж"),
                ),
                (
                    "frequency",
                    models.CharField(max_length=50, verbose_name="Частота в неделю"),
                ),
                (
                    "duration",
                    models.CharField(
                        max_length=50, verbose_name="Длительность тренировки"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Место тренировок"),
                ),
                (
                    "equipment",
                    models.CharField(max_length=100, verbose_name="Инвентарь"),
                ),
                (
                    "goal",
                    models.CharField(max_length=100, verbose_name="Основная цель"),
                ),
                (
                    "workout_types",
                    models.JSONField(default=list, verbose_name="Виды нагрузки"),
                ),
                (
                    "focus",
                    models.CharField(blank=True, max_length=255, verbose_name="Акцент"),
                ),
                ("muscles", models.JSONField(default=list, verbose_name="Группы мышц")),
                (
                    "intensity",
                    models.CharField(max_length=100, verbose_name="Интенсивность"),
                ),
                (
                    "body_type",
                    models.CharField(max_length=100, verbose_name="Тип телосложения"),
                ),
                ("gender", models.CharField(max_length=20, verbose_name="Пол")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="Вес (кг)"),
                ),
                (
                    "height",
                    models.FloatField(blank=True, null=True, verbose_name="Рост (см)"),
                ),
                ("injuries", models.JSONField(default=list, verbose_name="Травмы")),
                ("notes", models.TextField(blank=True, verbose_name="Доп. информация")),
                (
                    "result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Результат (JSON)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Генерируется"),
                            ("done", "Готова"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_msg", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ["-created_at"],
            },
        ),
    ]
